---
- name: Install required packages.
  yum:
    name:
      - wget
      - openssh-server
      - vim
    state: present

- name: Add ansible user
  user:
    name: "{{ bootstrap_ansible_user }}"
    create_home: true
    groups:
      - wheel
    shell: /bin/bash
    append: true
    state: present
